### ISSUE TITLE
Convert Winston functions to Gadfly

### ISSUE THREAD

**Issue by codles** [codles/EEG.jl#31]
Reduce dependencies as discussed in #25

**Comment by codles** [comment]
List of functions to convert
- [ ] dat plotting
- [ ] dipole plotting

**Comment by codles** [comment]
The source plotting can't be converted over until the size can be set in gadfly

**Comment by brk00** [comment]
Is it into Gadfly's roadmap?

**Comment by codles** [comment]
Closed in favour of #58
