### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by codles** [codles/EEG.jl#33]
Most of this code could be used with MEG or other electrophysiological data.
Which is why I kept the low level functions generic and then placed types on top of these functions.
Should I change the name to `Electrophysiology.jl` and register this package to METADATA ?

**Comment by codles** [comment]
@brk00 @dcjones any opinion here?

**Comment by prcastro** [comment]
I agree we should change the name, but maybe `Electrophysiology.jl` is a bit too long. But if you're confortable with that, let's do it!

**Comment by codles** [comment]
Decided against the name change. Package submitted to METADATA
